### ISSUE TITLE
Single .glyphs file for Roman and Italic

### ISSUE THREAD

**Issue by davelab6** [cadsondemak/Srisakdi#4]
https://github.com/cadsondemak/Srisakdi/tree/master/source contains one `.glyphs` file for each style, but this is not good; there should be a single `.glyphs` file for Roman and Italic, with Masters and Instances set up inside it for each style.

**Comment by AnuthinWongsunkakon** [comment]
I have checked with @suppakit- and that we originally have done it in single file. This is not a problem. Can push the new all in one up easily.

**Comment by suppakit-** [comment]
รับทราบครับ เดี๋ยวผมจะแพ็ค glyphs ไฟล์ใหม่ให้เป็นไฟล์เดียวครับ :D
