### ISSUE TITLE
Check fonts with Font Bakery and Marc Foley's Glyphs Checking Tool

### ISSUE THREAD

**Issue by davelab6** [cadsondemak/Srisakdi#5]
Please try to "pre check" your projects with https://github.com/m4rc1e/mf-glyphs-scripts/tree/master/QA on the glyphs files and https://github.com/googlefonts/fontbakery on the TTFs :) 

I'm CC'ing @felipesanches and @m4rc1e to this issue so that if you have any questions posted here, they can answer :)

**Comment by felipesanches** [comment]
Yeah! Feel free to let us know if you have any feedback or questions regarding our tools. We'll be glad to help!

**Comment by suppakit-** [comment]
Hi, Could you please walk me through how to install Font Bakery in my iMac and Macbook Pro. I am using iMac running  MacOS Sierra and Macbook pro running High Sierra in case you need it to determine what should I do to install it. I could not figure out. We have been getting an error when we try to install it. Or should I just use the via web browser instead but I see that you discontinue the update. We have tried but not every fonts get the report back. Please advice.

**Comment by kanorider** [comment]
I have tried to install it using terminal but keep getting the same error. Need your advice on how to install this. Much appreciated.

**Comment by felipesanches** [comment]
I noticed that our install instructions for MacOSX are not ideal yet.

Let me try to gather more insight here, then. Can you tell me if this works for you?

Step 1:
```
# install os x developer tools and the homebrew package manager
xcode-select --install;
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)";
```

Step 2:
```
# then instal python version 2 so that we don't rely
# on the python interpreter originally shipped on MacOSX
brew install python2;
```

Step 3:
```
# and finally, use pip2 to install fontbakery
pip2 install -U fontbakery
```

**Look carefully!** The above commands are **not** identical to what you see in fontbakery's install instructions. Be sure that you tried exactly what is described here so that I can better understand what's going wrong for you. **Note:** I did try myself the commands listed above on a MacBook Pro and it worked for me.

**Comment by felipesanches** [comment]
Also, both of you @suppakit- and @kanorider mentioned "errors" but did not provide further info. Screenshots would be greatly appreciated in such occasions.

**Comment by kanorider** [comment]
this is an error when I try to upgrading to a newer version
<img width="849" alt="screen shot 2561-03-18 at 18 38 37" src="https://user-images.githubusercontent.com/12980226/37565414-af415254-2adb-11e8-8556-05471a009872.png">

**Comment by felipesanches** [comment]
@kanorider Have you tried this? https://github.com/cadsondemak/Srisakdi/issues/5#issuecomment-373989232

**Comment by kanorider** [comment]
@felipesanches oh sorry I forgot to updated you that now I can install it. Thank for your help.
I'm not sure how  to work with it properly so, tried with this command and it show this
<img width="568" alt="screen shot 2561-03-19 at 00 02 24" src="https://user-images.githubusercontent.com/12980226/37568607-055a2a5c-2b0a-11e8-9219-86b57aee3751.png">

**Comment by felipesanches** [comment]
@kanorider your message is a bit confusing. You say you now you were able to install it, but you also say you did not get it right, yet. Did you run the commands of the 3 steps described at https://github.com/cadsondemak/Srisakdi/issues/5#issuecomment-373989232 ?

**Comment by felipesanches** [comment]
@suppakit- could you please try https://github.com/cadsondemak/Srisakdi/issues/5#issuecomment-373989232 as well and send me screenshots of the result of running each of the 3 steps?

Please, let me know if that helps or not.

**Comment by AnuthinWongsunkakon** [comment]
@felipesanches I think.... @kanorider is trying to say is he installed it on his computer successfully but he is not sure it works properly because he tried to run it and get the message “Command not found”.

**Comment by felipesanches** [comment]
yeah.....

Screenshots of each relevant step would probably help here. As a general debugging principle, a programmer will be more likely to find a solution if the users provide abundant details on the problems they're facing.

@kanorider and @suppakit- Could you give me very detailed reports of the errors you're getting, please? This would ideally include e description of each thing you tried (in chronological order) and also what happened as a result of each step.

Also, images (screenshots) tend to be better than words in these cases.

**Comment by felipesanches** [comment]
So I would like to know if you all tried https://github.com/cadsondemak/Srisakdi/issues/5#issuecomment-373989232 and whether that worked or not (and how).

**Comment by suppakit-** [comment]
Thank you for your advice and a walk through. It is working now. If we run into any problem we will let you know. :D

**Comment by felipesanches** [comment]
I'm glad it worked. I'm assuming that the https://github.com/cadsondemak/Srisakdi/issues/5#issuecomment-373989232 was what you used to get it working and that I can update the description of install procedures on Fontbakery's README.md file to reflect that.

**Comment by kanorider** [comment]
@felipesanches Thank you for your help :)
