### ISSUE TITLE
Focus on Latin 

### ISSUE THREAD

**Issue by siringunkloy** [cadsondemak/Srisakdi#6]
![screen shot 2561-03-15 at 1 10 10 pm](https://user-images.githubusercontent.com/35678481/37448680-f88a9dd2-2859-11e8-92fe-b8d2d38be064.png)
![screen shot 2561-03-15 at 1 10 26 pm](https://user-images.githubusercontent.com/35678481/37448681-f8beaa96-2859-11e8-8c50-f407f01742d9.png)
สวัสดีค่ะ จากที่ทราบคือแบบตัวนี้เป็นตัวที่มีพื้นฐานมาจากลายมือ (Handwritten based) โดยมีภาพรวมเป็นเส้นต่อเนื่อง (Continuous strokes ) เลยมีคำถามและข้อคิดเห็นมาค่ะ :)
- เข้าใจว่าน่าจะต้องการจัดการ proportion ให้มีความสูงผอมเป็นไปในทิศทางเดียวกับในตัวไทย แต่ว่าในบางตัวอย่างเช่นตัว a, r ไม่แน่ใจว่าดูแคบไปรึเปล่าค่ะ และตัว g ไม่แน่ใจว่ากว้างไปไหมค่ะ 
- เพื่อไม่ให้เกิดการสะดุดไปจากระบบเส้นต่อเนื่องในภาพรวม ตรงด้านมุม eye ของตัว e  อาจจะต้องการมุมที่เป็น rounded นิดนึงรึเปล่าคะ และตัว K, k อาจจะโดดไปจากระบบในภาพรวมไหมคะ เพราะเป็นตัวที่ใช้ระบบต่อกิ่งแบบ Modular system อยู่ตัวเดียว
- อยากให้ช่วยเช็คตัวอักษรที่มีส่วน Apex กับ Vertex ในทั้งสองเวทดูค่ะ เท่าที่ดูไม่แน่ใจว่าตอนนี้ตามมุมจะเข้มไปรึเปล่า เช่นในตัว M,N,W,w ค่ะ 
ขอบคุณค่ะ

**Comment by AnuthinWongsunkakon** [comment]
แน่ๆ ดูแบบเร็วๆคือ descender มันน้อยไปนิดนะครับ ที่เหลือเดี๋ยวไปวงมาให้แล้วเอามาแปะครับ

**Comment by AnuthinWongsunkakon** [comment]
![37448681-f8beaa96-2859-11e8-8c50-f407f01742d9](https://user-images.githubusercontent.com/36420640/37558397-07020060-2a46-11e8-93c1-e61f3ab3d908.png)

**Comment by AnuthinWongsunkakon** [comment]
![37448681-f8beaa96-2859-11e8-8c50-f407f01742d9](https://user-images.githubusercontent.com/36420640/37558426-82062688-2a46-11e8-9b98-4bfa81bc2314.png)

**Comment by kanorider** [comment]
ขอบคุณสำหรับคำแนะนำครับ จะนำไปพิจรณาปรับตามครับ
